import { farFuture, recent, dateOnly } from '../helpers/time.helpers';

export function makeDriver(overrides?: Record<string, any>) {
  return {
    id: 1,
    driverId: 'drv-test-001',
    tenantId: 1,
    name: 'John Driver',
    licenseNumber: 'DL-123456789',
    licenseState: 'TX',
    phone: '555-000-0100',
    email: 'john.driver@test-trucking.com',
    cdlClass: 'A',
    endorsements: ['H', 'N'],
    status: 'ACTIVE',
    activatedAt: recent(),
    syncStatus: 'MANUAL_ENTRY',
    externalSource: null,
    externalDriverId: null,
    hosData: {},
    currentHoursDriven: 0,
    currentOnDutyTime: 0,
    currentHoursSinceBreak: 0,
    cycleHoursUsed: 0,
    homeTerminalTimezone: 'America/New_York',
    hireDate: dateOnly(recent()),
    medicalCardExpiry: dateOnly(farFuture()),
    cdlExpiry: dateOnly(farFuture()),
    mvrDate: dateOnly(recent()),
    drugTestDate: dateOnly(recent()),
    annualReviewDate: dateOnly(farFuture()),
    assignedVehicleId: null,
    assignedVehicle: null,
    _count: { loads: 0 },
    createdAt: recent(),
    updatedAt: recent(),
    ...overrides,
  };
}
