import { farFuture, recent } from '../helpers/time.helpers';

export function makeTrailer(overrides?: Record<string, any>) {
  return {
    id: 1,
    trailerId: 'TRL-TEST001',
    tenantId: 1,
    unitNumber: 'TRL-5301',
    make: 'Great Dane',
    model: 'Everest',
    year: 2023,
    vin: '1JJV532D4KL000123',
    licensePlate: 'TX-TRL-001',
    licensePlateState: 'TX',
    equipmentType: 'DRY_VAN',
    lengthFeet: 53,
    maxPayloadLbs: 44000,
    ownershipType: 'OWNED',
    reeferMake: null,
    reeferModel: null,
    reeferSerial: null,
    registrationExpiry: farFuture(),
    insuranceExpiry: farFuture(),
    annualInspectionDate: recent(),
    nextMaintenanceDate: farFuture(),
    notes: null,
    status: 'AVAILABLE',
    lifecycleStatus: 'ACTIVE',
    previousStatus: null,
    assignedVehicleId: null,
    assignedVehicle: null,
    externalTrailerId: null,
    externalSource: null,
    lastSyncedAt: null,
    eldTelematicsMetadata: null,
    deactivatedAt: null,
    deactivatedBy: null,
    deactivationReason: null,
    reactivatedAt: null,
    reactivatedBy: null,
    createdAt: recent(),
    updatedAt: recent(),
    ...overrides,
  };
}
