import * as fs from 'fs';
import * as path from 'path';

/**
 * Lock-in guardrail (PR 6/6 of the domain-enums series).
 *
 * Forbid hand-maintained Zod enums in `packages/shared-types/src/**` whose
 * name matches a generated Prisma enum at
 * `packages/shared-types/src/generated/prisma-enums.ts`. The codegen mirror
 * (auto-regenerated by `pnpm prisma:generate`) is the single source of truth
 * for any enum that's also a Prisma enum on the backend.
 *
 * Hand-written Zod enums are still fine for value spaces NOT backed by a
 * Prisma enum (e.g. lowercase wire formats, derived UI labels, free-form
 * registries). The check is name-based: a hand-written
 * `export const FooStatusSchema = z.enum([...])` collides with a generated
 * `export const FooStatusSchema = z.enum([...] as const)`.
 *
 * Allow-list below documents intentional exceptions where keeping the
 * hand-written one is correct (e.g. it lives in a different file with a
 * different value space, or the import shape is needed for legacy callers
 * that PR 6 cannot retire safely in a single change).
 */

const SHARED_TYPES_ROOT = path.resolve(__dirname, '..', '..', '..', '..', 'packages', 'shared-types', 'src');
const GENERATED_FILE = path.join(SHARED_TYPES_ROOT, 'generated', 'prisma-enums.ts');

/**
 * Names of hand-written Zod schemas that are intentionally retained even
 * though codegen also emits a same-named schema. Each entry must include a
 * one-line justification — reviewers reject additions without one.
 *
 * Format: `<SchemaName> → reason`
 *
 * Today this list captures the legacy state: ~46 hand-written Zod enums
 * that duplicate generated Prisma enums. Retiring them is a mechanical
 * sweep (each entry: replace `export const FooSchema = z.enum([...])`
 * with `export { FooSchema } from '../generated/prisma-enums'`, then sweep
 * import sites). PR 6 ships the guardrail; subsequent PRs retire entries
 * one domain at a time, removing them from this allow-list as they go.
 *
 * Adding a NEW entry to this list requires reviewer sign-off — the
 * default position is "if codegen emits it, use codegen."
 */
const ALLOW_LIST = new Map<string, string>([
  // ── Operations / Alerts ──────────────────────────────────────────────────
  // AlertPrioritySchema, AlertScopeSchema, AlertStatusSchema all retired —
  // re-exported from codegen mirror in operations/alert.schema.ts.
  // ── Desk ─────────────────────────────────────────────────────────────────
  // ApprovalDecisionSchema, LifecycleSchema, PrioritySchema, TriggerKindSchema,
  // TrustLevelSchema, MemoryScopeSchema, MemoryPolaritySchema all retired —
  // re-exported from codegen mirror in desk/enums.ts. The Memory schemas were
  // flipped to UPPER end-to-end (boundary `.toLowerCase()` translation removed)
  // so wire format and DB representation now agree.
  // ── Financials ───────────────────────────────────────────────────────────
  // BillingPath, DeductionType, FactoringTxnType, InvoiceStatus, LineItemType,
  // NoaStatus, PayStructureType, RecourseType, SettlementStatus all retired —
  // re-exported from codegen mirror in financials/{invoice,settlement,
  // factoring-transaction}.schema.ts.
  // ── Fleet ────────────────────────────────────────────────────────────────
  // ContactRole, DocumentStatus, TripStatus, CustomerStatus, CustomerType,
  // EquipmentType, LoadBillingStatus, LoadLegStatus, LoadStatus, LoadStopStatus,
  // MoneyCodeMethod, MoneyCodeStatus, OwnershipType, PaymentTerms,
  // RecurringLaneStatus, TrailerLifecycleStatus, TrailerStatus, VehicleStatus —
  // all retired, re-exported from codegen mirror across fleet/*.schema.ts.
  // ── Infrastructure / Notifications + Jobs ────────────────────────────────
  // JobStatusSchema, NotificationCategorySchema, NotificationTypeSchema all
  // retired in the shadow-sweep PR — they now re-export from the codegen mirror
  // in webhook.schema.ts. NotificationStatusSchema was renamed to
  // NotificationInboxStatusSchema (UI inbox state vs Prisma delivery state).
  // ── Integrations ─────────────────────────────────────────────────────────
  // IntegrationStatusSchema, IntegrationTypeSchema, IntegrationVendorSchema all
  // retired in the shadow-sweep PR — re-export from codegen mirror.
  // ── Operations / Shield ──────────────────────────────────────────────────
  // All 5 Shield schemas retired in the shadow-sweep PR — re-export from
  // codegen mirror in operations/shield.schema.ts.
  // ── Operations / Support ─────────────────────────────────────────────────
  // All 3 Support schemas retired in the shadow-sweep PR — re-export from
  // codegen mirror in operations/support.schema.ts.
  // ── Platform ─────────────────────────────────────────────────────────────
  // BundleFormatSchema, DriverPayTimingSchema, TenantPlanSchema all retired
  // in the shadow-sweep PR — re-export from codegen mirror.
  ['LeadStatusSchema', 'PR 6.X: hand-written in platform/lead.schema.ts (added by PR 5b promotion)'],
]);

/**
 * Schemas where the hand-written value set is INTENTIONALLY different from the
 * generated mirror (typically because the name collision is itself the bug —
 * the hand-written one models a different concept and should be renamed).
 * Adding here is a temporary measure: the entry should be removed once the
 * hand-written schema is renamed so it stops shadowing.
 */
const VALUE_DRIFT_RENAME_PENDING = new Map<string, string>([
  // Empty — no allow-listed schemas have value drift today. The Memory pair
  // (MemoryScope/MemoryPolarity) was the last entry; resolved by flipping
  // the Memory wire format to UPPER end-to-end. The map is retained as a
  // mechanism for future intentional-drift cases.
]);

interface DuplicateFinding {
  schemaName: string;
  handWrittenFile: string;
  generatedSchemaLine: number;
}

function listFilesRecursive(dir: string, ignore: Set<string>): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (ignore.has(full)) continue;
    if (entry.isDirectory()) {
      out.push(...listFilesRecursive(full, ignore));
    } else if (entry.isFile() && (entry.name.endsWith('.ts') || entry.name.endsWith('.tsx'))) {
      out.push(full);
    }
  }
  return out;
}

/**
 * Parse the literal values of a `z.enum([...])` declaration starting at the
 * given offset in the source. Returns the values in declaration order or
 * null if the declaration could not be parsed (e.g. dynamic values).
 */
function parseEnumValuesAt(src: string, offsetAfterEnumOpen: number): string[] | null {
  // Find the matching `])` for this `z.enum([` opener.
  let depth = 1;
  let i = offsetAfterEnumOpen;
  while (i < src.length && depth > 0) {
    const c = src[i];
    if (c === '[') depth++;
    else if (c === ']') depth--;
    i++;
  }
  if (depth !== 0) return null;
  const inside = src.slice(offsetAfterEnumOpen, i - 1);
  // Match string literals: 'foo', "foo", `foo`. Reject if any non-string token slipped in.
  const valueRe = /(['"`])([^'"`]*)\1/g;
  const values: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = valueRe.exec(inside))) values.push(m[2]);
  return values.length > 0 ? values : null;
}

interface SchemaDecl {
  values: string[];
  line: number;
}

function collectEnumDecls(src: string): Map<string, SchemaDecl> {
  const out = new Map<string, SchemaDecl>();
  const re = /^export const (\w+Schema)\s*=\s*z\.enum\(\[/gm;
  let match: RegExpExecArray | null;
  while ((match = re.exec(src))) {
    const name = match[1];
    const values = parseEnumValuesAt(src, re.lastIndex);
    if (!values) continue;
    const line = src.slice(0, match.index).split('\n').length;
    out.set(name, { values, line });
  }
  return out;
}

describe('No duplicate hand-maintained Zod enums', () => {
  let generatedSchemas: Map<string, SchemaDecl>;
  let handWrittenFiles: string[];

  beforeAll(() => {
    const generatedSrc = fs.readFileSync(GENERATED_FILE, 'utf8');
    generatedSchemas = collectEnumDecls(generatedSrc);

    // List all .ts files under shared-types/src EXCEPT the generated dir.
    handWrittenFiles = listFilesRecursive(SHARED_TYPES_ROOT, new Set([path.join(SHARED_TYPES_ROOT, 'generated')]));
  });

  it('hand-written shared-types files do not export Zod schemas that shadow generated ones', () => {
    const findings: DuplicateFinding[] = [];

    for (const file of handWrittenFiles) {
      const src = fs.readFileSync(file, 'utf8');
      const decls = collectEnumDecls(src);
      for (const [name] of decls) {
        if (!generatedSchemas.has(name)) continue;
        if (ALLOW_LIST.has(name)) continue;
        findings.push({
          schemaName: name,
          handWrittenFile: path.relative(SHARED_TYPES_ROOT, file),
          generatedSchemaLine: generatedSchemas.get(name).line,
        });
      }
    }

    if (findings.length > 0) {
      const messages = findings.map(
        (f) =>
          `  - ${f.schemaName}: hand-written in ${f.handWrittenFile}, also generated at generated/prisma-enums.ts:${f.generatedSchemaLine}. Delete the hand-written one and import from the generated mirror, or add a documented justification to ALLOW_LIST.`,
      );
      throw new Error(
        `Found ${findings.length} duplicate Zod enum(s) shadowing generated Prisma enums:\n${messages.join('\n')}`,
      );
    }
  });

  /**
   * Value-set drift check (added after a P0 caught in post-PR-6 audit:
   * `AlertPrioritySchema` was allow-listed as "duplicate name OK," but the
   * hand-written values were lowercase while the generated values were
   * UPPER. The lock-in spec passed; the UI silently rendered no priority
   * styling because `Record<AlertPriority, ...>` was keyed wrong.)
   *
   * Rule: any allow-listed duplicate-name schema MUST have the same value
   * set as the generated mirror. If you need a different value space,
   * rename the schema — don't shadow.
   */
  it('allow-listed hand-written schemas have the same values as the generated mirror', () => {
    const drift: { name: string; file: string; handValues: string[]; generatedValues: string[] }[] = [];

    for (const file of handWrittenFiles) {
      const src = fs.readFileSync(file, 'utf8');
      const decls = collectEnumDecls(src);
      for (const [name, decl] of decls) {
        if (!generatedSchemas.has(name)) continue;
        if (!ALLOW_LIST.has(name)) continue; // non-allow-listed are caught above
        if (VALUE_DRIFT_RENAME_PENDING.has(name)) continue; // intentional drift, awaiting rename
        const generated = generatedSchemas.get(name);
        const sameValues =
          decl.values.length === generated.values.length && decl.values.every((v, i) => v === generated.values[i]);
        if (!sameValues) {
          drift.push({
            name,
            file: path.relative(SHARED_TYPES_ROOT, file),
            handValues: decl.values,
            generatedValues: generated.values,
          });
        }
      }
    }

    if (drift.length > 0) {
      const messages = drift.map(
        (d) =>
          `  - ${d.name} in ${d.file}: hand=[${d.handValues.join('|')}] vs generated=[${d.generatedValues.join('|')}]. Either align values with the generated mirror, or rename the hand-written schema so it doesn't shadow.`,
      );
      throw new Error(
        `Found ${drift.length} allow-listed schema(s) whose values drift from the generated Prisma mirror:\n${messages.join(
          '\n',
        )}`,
      );
    }
  });
});
