import type { Metadata } from 'next';
import { CONTACTS } from '@appshore/web-core/shared/lib/contacts';

export const metadata: Metadata = {
  title: 'Privacy Policy',
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <h1>Privacy Policy</h1>
      <p>Last updated: {new Date().getFullYear()}</p>

      <h2>1. Information we collect</h2>
      <p>
        We collect the information you provide when you create an account (name, email address, phone number, company
        name), information generated by your use of the service (usage logs, device and browser metadata), and any
        content you store in the platform.
      </p>

      <h2>2. How we use information</h2>
      <ul>
        <li>To provide, operate, and improve the service.</li>
        <li>To communicate with you about your account, billing, and support requests.</li>
        <li>To secure the service and prevent abuse.</li>
      </ul>

      <h2>3. Sharing</h2>
      <p>
        We do not sell your personal information. We share data only with service providers that help us operate the
        platform (hosting, payments, communications), under contractual confidentiality obligations, or when required by
        law.
      </p>

      <h2>4. Data retention</h2>
      <p>
        We retain account data for as long as your account is active and as needed to comply with legal obligations. You
        may request deletion of your account and associated data at any time.
      </p>

      <h2 id="ccpa">5. Your privacy rights (including CCPA)</h2>
      <p>
        Depending on where you live, you may have rights to access, correct, export, or delete your personal
        information, and to opt out of the sale or sharing of personal information. We do not sell personal information.
        To exercise any of these rights, contact us at {CONTACTS.legal}.
      </p>

      <h2>6. Contact</h2>
      <p>
        Questions about this policy? Email {CONTACTS.legal} or {CONTACTS.support}.
      </p>
    </>
  );
}
