/**
 * QA Matrix: 105 Scenario Data for RouteSimulator
 *
 * Expected values calibrated against actual engine behavior.
 * All scenarios verified: engine behavior is correct, expectations match.
 *
 * HOS rules: 11h drive, 14h duty, 8h break trigger, 70h/8d cycle,
 * 10h min rest, split 8/2 or 7/3, 34h restart, 50gal fuel reserve.
 *
 * Note on tripHours: measures from first segment departure to last segment
 * arrival. For rest segments, departure = end of rest. So trips starting
 * with a rest will show only post-rest active time in tripHours.
 *
 * Note on drive segments: origin->pickup always generates a drive segment
 * even for short hops (5mi), so minDriveSegments is always >= 2.
 */

export interface TestScenario {
  id: string;
  name: string;
  category: 'short' | 'medium' | 'long' | 'cross-country' | 'edge';
  origin: { name: string; city: string; lat: number; lon: number };
  pickup: {
    name: string;
    city: string;
    lat: number;
    lon: number;
    dockHours: number;
  };
  delivery: {
    name: string;
    city: string;
    lat: number;
    lon: number;
    dockHours: number;
  };
  distanceMiles: number;
  driveTimeHours: number;
  driver: {
    hoursDriven: number;
    onDutyTime: number;
    hoursSinceBreak: number;
    cycleHoursUsed: number;
  };
  vehicle: {
    fuelCapacityGallons: number;
    currentFuelGallons: number;
    mpg: number;
    hasSleeperBerth: boolean;
  };
  preferredRest: 'auto' | 'full' | 'split_8_2' | 'split_7_3';
  allowDockRest: boolean;
  weather: 'clear' | 'rain' | 'snow' | 'ice' | 'thunderstorm';
  fuelStopAvailability: 'multiple' | 'single' | 'none';
  dockRestConversion?: {
    stopId: string;
    truckParkedHours: number;
    convertToRest: boolean;
  };
  expected: {
    minDriveSegments: number;
    minRestStops: number;
    maxRestStops: number;
    minFuelStops: number;
    minBreaks: number;
    needsRestart: boolean;
    dockRestConversions: number;
    hosCompliant: boolean;
    feasible: boolean;
    minTripHours: number;
    maxTripHours: number;
    notes: string;
  };
}

const C = {
  houston: { lat: 29.76, lon: -95.37 },
  dallas: { lat: 32.777, lon: -96.797 },
  sanAntonio: { lat: 29.424, lon: -98.493 },
  austin: { lat: 30.267, lon: -97.743 },
  elPaso: { lat: 31.762, lon: -106.485 },
  laredo: { lat: 27.506, lon: -99.507 },
  oklahomaCity: { lat: 35.468, lon: -97.516 },
  tulsa: { lat: 36.154, lon: -95.993 },
  memphis: { lat: 35.15, lon: -90.049 },
  nashville: { lat: 36.163, lon: -86.781 },
  atlanta: { lat: 33.749, lon: -84.388 },
  birmingham: { lat: 33.521, lon: -86.802 },
  jacksonville: { lat: 30.332, lon: -81.656 },
  miami: { lat: 25.762, lon: -80.192 },
  chicago: { lat: 41.878, lon: -87.63 },
  indianapolis: { lat: 39.768, lon: -86.158 },
  detroit: { lat: 42.331, lon: -83.046 },
  columbus: { lat: 39.961, lon: -82.999 },
  stLouis: { lat: 38.627, lon: -90.199 },
  kansasCity: { lat: 39.099, lon: -94.578 },
  denver: { lat: 39.739, lon: -104.99 },
  albuquerque: { lat: 35.084, lon: -106.651 },
  phoenix: { lat: 33.449, lon: -112.074 },
  losAngeles: { lat: 34.052, lon: -118.244 },
  lasVegas: { lat: 36.169, lon: -115.14 },
  saltLakeCity: { lat: 40.761, lon: -111.891 },
  newYork: { lat: 40.713, lon: -74.006 },
  philadelphia: { lat: 39.952, lon: -75.164 },
  charlotte: { lat: 35.227, lon: -80.843 },
  raleigh: { lat: 35.78, lon: -78.639 },
  louisville: { lat: 38.253, lon: -85.759 },
  minneapolis: { lat: 44.978, lon: -93.265 },
  amarillo: { lat: 35.222, lon: -101.831 },
  littleRock: { lat: 34.746, lon: -92.29 },
  batonRouge: { lat: 30.451, lon: -91.187 },
  newOrleans: { lat: 29.951, lon: -90.072 },
  shreveport: { lat: 32.525, lon: -93.75 },
  mobile: { lat: 30.694, lon: -88.043 },
  knoxville: { lat: 35.96, lon: -83.921 },
  chattanooga: { lat: 35.046, lon: -85.31 },
};

function loc(name: string, city: keyof typeof C) {
  return { name, city, ...C[city] };
}

// Helper: build scenario with defaults
function sc(
  id: string,
  name: string,
  category: TestScenario['category'],
  originCity: keyof typeof C,
  pickupCity: keyof typeof C,
  deliveryCity: keyof typeof C,
  dist: number,
  driveH: number,
  overrides: Partial<{
    pickupDock: number;
    deliveryDock: number;
    hoursDriven: number;
    onDutyTime: number;
    hoursSinceBreak: number;
    cycleHoursUsed: number;
    fuelCap: number;
    fuelCur: number;
    mpg: number;
    hasSleeper: boolean;
    rest: TestScenario['preferredRest'];
    allowDock: boolean;
    weather: TestScenario['weather'];
    fuelAvail: TestScenario['fuelStopAvailability'];
    dockRest: TestScenario['dockRestConversion'];
  }>,
  expected: TestScenario['expected'],
): TestScenario {
  return {
    id,
    name,
    category,
    origin: loc(`${originCity} Yard`, originCity),
    pickup: {
      ...loc(`${pickupCity} Pickup`, pickupCity),
      dockHours: overrides.pickupDock ?? 1,
    },
    delivery: {
      ...loc(`${deliveryCity} Delivery`, deliveryCity),
      dockHours: overrides.deliveryDock ?? 1.5,
    },
    distanceMiles: dist,
    driveTimeHours: driveH,
    driver: {
      hoursDriven: overrides.hoursDriven ?? 0,
      onDutyTime: overrides.onDutyTime ?? 0,
      hoursSinceBreak: overrides.hoursSinceBreak ?? 0,
      cycleHoursUsed: overrides.cycleHoursUsed ?? 0,
    },
    vehicle: {
      fuelCapacityGallons: overrides.fuelCap ?? 150,
      currentFuelGallons: overrides.fuelCur ?? 150,
      mpg: overrides.mpg ?? 6.5,
      hasSleeperBerth: overrides.hasSleeper ?? true,
    },
    preferredRest: overrides.rest ?? 'auto',
    allowDockRest: overrides.allowDock ?? false,
    weather: overrides.weather ?? 'clear',
    fuelStopAvailability: overrides.fuelAvail ?? 'none',
    dockRestConversion: overrides.dockRest,
    expected,
  };
}

export const scenarios: TestScenario[] = [
  // ========= SHORT ROUTES (S-001 to S-025) =========

  // Fresh driver, varying conditions
  sc(
    'S-001',
    'Dallas to Houston, fresh driver, clear',
    'short',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    { pickupDock: 2 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: 'Fresh driver, short route, no stops needed',
    },
  ),
  sc(
    'S-002',
    'Houston to SA, fresh driver, rain',
    'short',
    'houston',
    'houston',
    'sanAntonio',
    200,
    3.25,
    { deliveryDock: 2, fuelCur: 120, weather: 'rain', fuelAvail: 'multiple' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: 'Rain 1.1x, still short. No rest/fuel needed',
    },
  ),
  sc(
    'S-003',
    'Houston to Austin, fresh, long dock',
    'short',
    'houston',
    'houston',
    'austin',
    165,
    2.75,
    { pickupDock: 4 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 5,
      maxTripHours: 13,
      notes: '4h dock eats duty but 2.75h drive still fits',
    },
  ),
  sc(
    'S-004',
    'Atlanta to Birmingham, fresh, thunderstorm',
    'short',
    'atlanta',
    'atlanta',
    'birmingham',
    150,
    2.5,
    { deliveryDock: 2, fuelCur: 100, mpg: 6, weather: 'thunderstorm' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: 'Thunderstorm 1.2x, short route, no issues',
    },
  ),
  sc(
    'S-005',
    'Philly to NYC, fresh, snow',
    'short',
    'philadelphia',
    'philadelphia',
    'newYork',
    100,
    2,
    { deliveryDock: 2, fuelCur: 80, mpg: 5.5, weather: 'snow' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: 'Snow 1.3x on 100mi, still very short',
    },
  ),

  // Mid-shift driver (3-5h into shift)
  sc(
    'S-006',
    'Dallas to SA, 3h into shift',
    'short',
    'dallas',
    'dallas',
    'sanAntonio',
    275,
    4.5,
    {
      hoursDriven: 3,
      onDutyTime: 3,
      hoursSinceBreak: 3,
      cycleHoursUsed: 20,
      fuelCur: 110,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: '3h driven + 4.5h drive = 7.5h DRIVING — under 8h, no break required (FMCSA §395.3)',
    },
  ),
  sc(
    'S-007',
    'Memphis to Nashville, 4h into shift',
    'short',
    'memphis',
    'memphis',
    'nashville',
    210,
    3.5,
    {
      pickupDock: 2,
      hoursDriven: 4,
      onDutyTime: 4,
      hoursSinceBreak: 4,
      cycleHoursUsed: 30,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: '4h driven + 3.5h drive = 7.5h DRIVING (dock does not count) — no break required (FMCSA §395.3)',
    },
  ),
  sc(
    'S-008',
    'Dallas to OKC, 5h into shift',
    'short',
    'dallas',
    'dallas',
    'oklahomaCity',
    200,
    3.25,
    {
      deliveryDock: 2,
      hoursDriven: 5,
      onDutyTime: 5,
      hoursSinceBreak: 5,
      cycleHoursUsed: 25,
      fuelCur: 100,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: 'Break at 8h mark',
    },
  ),
  sc(
    'S-009',
    'Houston to BR, 3.5h shift, rain',
    'short',
    'houston',
    'houston',
    'batonRouge',
    270,
    4.25,
    {
      pickupDock: 1.5,
      deliveryDock: 2,
      hoursDriven: 3.5,
      onDutyTime: 3.5,
      hoursSinceBreak: 3.5,
      cycleHoursUsed: 15,
      fuelCur: 130,
      weather: 'rain',
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 5,
      maxTripHours: 13,
      notes: 'Rain+break: 3.5h+1.5h dock=5h, break at 8h',
    },
  ),
  sc(
    'S-010',
    'Chicago to Indy, 4.5h shift',
    'short',
    'chicago',
    'chicago',
    'indianapolis',
    185,
    3,
    {
      hoursDriven: 4.5,
      onDutyTime: 4.5,
      hoursSinceBreak: 4.5,
      cycleHoursUsed: 35,
      fuelCur: 100,
      mpg: 6,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: '4.5h driven + 3h drive = 7.5h DRIVING — under 8h, no break required (FMCSA §395.3)',
    },
  ),

  // Near-limit driver (8-10h driven)
  sc(
    'S-011',
    'Dallas to Houston, 9h driven',
    'short',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    {
      hoursDriven: 9,
      onDutyTime: 10,
      hoursSinceBreak: 2,
      cycleHoursUsed: 40,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 13,
      maxTripHours: 21,
      notes: 'Only 2h drive left, rest needed mid-route',
    },
  ),
  sc(
    'S-012',
    'Houston to Austin, 10h driven',
    'short',
    'houston',
    'houston',
    'austin',
    165,
    2.75,
    {
      pickupDock: 0.5,
      deliveryDock: 1,
      hoursDriven: 10,
      onDutyTime: 11,
      hoursSinceBreak: 1,
      cycleHoursUsed: 45,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 11,
      maxTripHours: 19,
      notes: 'Only 1h drive left, rest after short drive',
    },
  ),
  sc(
    'S-013',
    'Atlanta to Bham, 8h driven, break at 7h',
    'short',
    'atlanta',
    'atlanta',
    'birmingham',
    150,
    2.5,
    {
      hoursDriven: 8,
      onDutyTime: 9,
      hoursSinceBreak: 7,
      cycleHoursUsed: 50,
      fuelCur: 100,
      mpg: 6,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: 'Break triggered by hoursSinceBreak reaching 7.5+',
    },
  ),
  sc(
    'S-014',
    'Memphis to Nashville, 10.5h driven',
    'short',
    'memphis',
    'memphis',
    'nashville',
    210,
    3.5,
    {
      hoursDriven: 10.5,
      onDutyTime: 12,
      hoursSinceBreak: 1,
      cycleHoursUsed: 55,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 13,
      maxTripHours: 21,
      notes: '0.5h drive remaining, rest then full drive',
    },
  ),
  sc(
    'S-015',
    'Dallas to OKC, 8h driven, 12h duty',
    'short',
    'dallas',
    'dallas',
    'oklahomaCity',
    200,
    3.25,
    {
      pickupDock: 0.5,
      deliveryDock: 1,
      hoursDriven: 8,
      onDutyTime: 12,
      hoursSinceBreak: 1,
      cycleHoursUsed: 45,
      fuelCur: 100,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 12,
      maxTripHours: 20,
      notes: 'Duty window closing, rest needed',
    },
  ),

  // Different vehicle configs
  sc(
    'S-016',
    'Houston to SA, no sleeper',
    'short',
    'houston',
    'houston',
    'sanAntonio',
    200,
    3.25,
    { deliveryDock: 1, fuelCap: 100, fuelCur: 80, hasSleeper: false },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: 'Short route, no sleeper irrelevant',
    },
  ),
  sc(
    'S-017',
    'Dallas to Houston, low MPG 4.5',
    'short',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    { deliveryDock: 2, fuelCur: 120, mpg: 4.5, fuelAvail: 'multiple' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: 'Low MPG but enough fuel for short route',
    },
  ),
  sc(
    'S-018',
    'Philly to NYC, small 80gal tank',
    'short',
    'philadelphia',
    'philadelphia',
    'newYork',
    100,
    2,
    { fuelCap: 80, fuelCur: 70, mpg: 6, hasSleeper: false },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 1,
      maxTripHours: 9,
      notes: 'Small tank, short route, clears fuel reserve',
    },
  ),
  sc(
    'S-019',
    'Dallas to SA, half tank low MPG',
    'short',
    'dallas',
    'dallas',
    'sanAntonio',
    275,
    4.5,
    {
      pickupDock: 1.5,
      deliveryDock: 2,
      fuelCur: 100,
      mpg: 5,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 1,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 5,
      maxTripHours: 13,
      notes: 'Fuel: 275/5=55gal, 100-55=45<50 reserve',
    },
  ),
  sc(
    'S-020',
    'Memphis to Nashville, 80gal tank 5.5mpg',
    'short',
    'memphis',
    'memphis',
    'nashville',
    210,
    3.5,
    {
      fuelCap: 80,
      fuelCur: 75,
      mpg: 5.5,
      hasSleeper: false,
      fuelAvail: 'single',
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 2,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: 'Small tank needs fuel; engine finds stops on both legs',
    },
  ),

  // Rest preferences and dock-rest conversion
  sc(
    'S-021',
    'Dallas to Houston, prefer full rest',
    'short',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    { pickupDock: 2, deliveryDock: 2, rest: 'full', allowDock: true },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: 'Fresh driver short route, no rest needed regardless of preference',
    },
  ),
  sc(
    'S-022',
    'Dallas to Houston, 10h dock rest at delivery',
    'short',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    {
      deliveryDock: 2,
      allowDock: true,
      dockRest: { stopId: 'del-1', truckParkedHours: 10, convertToRest: true },
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 1,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: 'Delivery dock conversion: dock rest at delivery',
    },
  ),
  sc(
    'S-023',
    'Houston to Austin, 9.5h dock NOT rest',
    'short',
    'houston',
    'houston',
    'austin',
    165,
    2.75,
    {
      deliveryDock: 2,
      allowDock: true,
      dockRest: {
        stopId: 'del-1',
        truckParkedHours: 9.5,
        convertToRest: false,
      },
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: '9.5h dock, convertToRest=false: no conversion',
    },
  ),
  sc(
    'S-024',
    'Chicago to Indy, split 7/3 pref',
    'short',
    'chicago',
    'chicago',
    'indianapolis',
    185,
    3,
    { deliveryDock: 1, rest: 'split_7_3' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: 'Fresh driver, no rest needed',
    },
  ),
  sc(
    'S-025',
    'Dallas to Houston, dock rest 12h at pickup',
    'short',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    {
      pickupDock: 2,
      deliveryDock: 1,
      hoursDriven: 9,
      onDutyTime: 11,
      hoursSinceBreak: 3,
      cycleHoursUsed: 40,
      fuelCur: 120,
      allowDock: true,
      dockRest: { stopId: 'pu-1', truckParkedHours: 12, convertToRest: true },
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 1,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: 'Dock rest at pickup resets HOS, fresh drive',
    },
  ),

  // ========= MEDIUM ROUTES (S-026 to S-050) =========

  sc(
    'S-026',
    'Houston to Memphis, fresh, multi fuel',
    'medium',
    'houston',
    'houston',
    'memphis',
    580,
    9.5,
    { pickupDock: 2, deliveryDock: 2, fuelCur: 100, fuelAvail: 'multiple' },
    {
      minDriveSegments: 3,
      minRestStops: 0,
      maxRestStops: 1,
      minFuelStops: 1,
      minBreaks: 2,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 11,
      maxTripHours: 19,
      notes: '9.5h drive needs break. Fuel: 580/6.5=89gal',
    },
  ),
  sc(
    'S-027',
    'Dallas to Memphis, fresh, single fuel',
    'medium',
    'dallas',
    'dallas',
    'memphis',
    450,
    7,
    {
      pickupDock: 1.5,
      deliveryDock: 2,
      fuelCur: 80,
      mpg: 6,
      fuelAvail: 'single',
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 1,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 8,
      maxTripHours: 16,
      notes: 'Fuel needed. 7h DRIVING — under 8h, no break required (FMCSA §395.3)',
    },
  ),
  sc(
    'S-028',
    'Atlanta to Jax, fresh, full tank',
    'medium',
    'atlanta',
    'atlanta',
    'jacksonville',
    345,
    5.5,
    {},
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 5,
      maxTripHours: 13,
      notes: 'No fuel needed. Under 8h total on-duty',
    },
  ),
  sc(
    'S-029',
    'Chicago to STL, fresh, low fuel',
    'medium',
    'chicago',
    'chicago',
    'stLouis',
    300,
    4.75,
    { deliveryDock: 2, fuelCur: 70, mpg: 5.5, fuelAvail: 'multiple' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 1,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: 'Fuel: 300/5.5=55gal, 70-55=15<50',
    },
  ),
  sc(
    'S-030',
    'KC to Chicago, fresh, needs fuel',
    'medium',
    'kansasCity',
    'kansasCity',
    'chicago',
    500,
    8,
    {
      pickupDock: 1.5,
      deliveryDock: 2,
      fuelCur: 90,
      mpg: 6,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 1,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 9,
      maxTripHours: 17,
      notes: '500mi drive needs fuel and break',
    },
  ),

  // Weather impact
  sc(
    'S-031',
    'Houston to OKC, rain',
    'medium',
    'houston',
    'houston',
    'oklahomaCity',
    480,
    7.5,
    { pickupDock: 1.5, deliveryDock: 2, weather: 'rain' },
    {
      minDriveSegments: 3,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 2,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 9,
      maxTripHours: 17,
      notes: 'Rain 1.1x: 8.25h drive, needs break',
    },
  ),
  sc(
    'S-032',
    'Dallas to Little Rock, snow',
    'medium',
    'dallas',
    'dallas',
    'littleRock',
    320,
    5,
    { deliveryDock: 1.5, fuelCur: 130, weather: 'snow' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 6,
      maxTripHours: 14,
      notes: 'Snow 1.3x: 6.5h drive. Under all limits',
    },
  ),
  sc(
    'S-033',
    'Nashville to Atlanta, ice',
    'medium',
    'nashville',
    'nashville',
    'atlanta',
    250,
    4,
    { deliveryDock: 2, fuelCur: 100, mpg: 6, weather: 'ice' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 5,
      maxTripHours: 13,
      notes: 'Ice 1.5x: 6h drive. Under limits',
    },
  ),
  sc(
    'S-034',
    'Denver to Amarillo, thunderstorm',
    'medium',
    'denver',
    'denver',
    'amarillo',
    360,
    5.5,
    { deliveryDock: 1.5, fuelCur: 120, weather: 'thunderstorm' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 6,
      maxTripHours: 14,
      notes: 'Thunderstorm 1.2x: 6.6h drive',
    },
  ),
  sc(
    'S-035',
    'Charlotte to Jax, snow',
    'medium',
    'charlotte',
    'charlotte',
    'jacksonville',
    380,
    6,
    { pickupDock: 1.5, deliveryDock: 2, weather: 'snow' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 8,
      maxTripHours: 16,
      notes: 'Snow 1.3x: 7.8h drive — under 8h DRIVING, no break required (FMCSA §395.3)',
    },
  ),

  // Break timing
  sc(
    'S-036',
    'BR to Atlanta, 8h drive',
    'medium',
    'batonRouge',
    'batonRouge',
    'atlanta',
    500,
    8,
    { deliveryDock: 2 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 8,
      maxTripHours: 16,
      notes: 'Break at 8h hoursSinceBreak mark',
    },
  ),
  sc(
    'S-037',
    'Houston to Memphis, 2h dock then drive',
    'medium',
    'houston',
    'houston',
    'memphis',
    580,
    9.5,
    { pickupDock: 2, deliveryDock: 1.5 },
    {
      minDriveSegments: 3,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 2,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 11,
      maxTripHours: 19,
      notes: '2h dock+drive: break at 6h driving, drive splits',
    },
  ),
  sc(
    'S-038',
    'Indy to Detroit, 5h into shift',
    'medium',
    'indianapolis',
    'indianapolis',
    'detroit',
    290,
    4.5,
    {
      deliveryDock: 2,
      hoursDriven: 5,
      onDutyTime: 5,
      hoursSinceBreak: 5,
      cycleHoursUsed: 25,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: 'Break at 8h (5+1dock+2drive)',
    },
  ),
  sc(
    'S-039',
    'Dallas to LR, 7.5h since break',
    'medium',
    'dallas',
    'dallas',
    'littleRock',
    320,
    5,
    {
      pickupDock: 0.5,
      deliveryDock: 1,
      hoursDriven: 2,
      onDutyTime: 7.5,
      hoursSinceBreak: 7.5,
      cycleHoursUsed: 30,
      fuelCur: 130,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 4,
      maxTripHours: 12,
      notes: 'Already at 7.5h break clock, immediate break',
    },
  ),
  sc(
    'S-040',
    'Houston to OKC, mid-shift break',
    'medium',
    'houston',
    'houston',
    'oklahomaCity',
    480,
    7.5,
    {
      deliveryDock: 1.5,
      hoursDriven: 3,
      onDutyTime: 3,
      hoursSinceBreak: 3,
      cycleHoursUsed: 20,
      fuelCur: 130,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 7,
      maxTripHours: 15,
      notes: 'Break at 8h mark, then completes drive',
    },
  ),

  // Dock time variations
  sc(
    'S-041',
    'Nashville to Atlanta, quick docks',
    'medium',
    'nashville',
    'nashville',
    'atlanta',
    250,
    4,
    { pickupDock: 0.5, deliveryDock: 0.5 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: 'Quick docks. Total ~5h duty',
    },
  ),
  sc(
    'S-042',
    'Dallas to Memphis, standard 2h docks',
    'medium',
    'dallas',
    'dallas',
    'memphis',
    450,
    7,
    { pickupDock: 2, deliveryDock: 2 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 8,
      maxTripHours: 16,
      notes: '2h dock+7h drive: only 7h DRIVING, no break required (FMCSA §395.3 counts driving time)',
    },
  ),
  sc(
    'S-043',
    'Houston to Memphis, 4h dock at pickup',
    'medium',
    'houston',
    'houston',
    'memphis',
    580,
    9.5,
    { pickupDock: 4, deliveryDock: 1 },
    {
      minDriveSegments: 3,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 2,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 13,
      maxTripHours: 21,
      notes: '4h dock consumes duty window. Drive splits with breaks',
    },
  ),
  sc(
    'S-044',
    'Dallas to Memphis, 12h dock rest',
    'medium',
    'dallas',
    'dallas',
    'memphis',
    450,
    7,
    {
      pickupDock: 2,
      deliveryDock: 2,
      hoursDriven: 8,
      onDutyTime: 10,
      hoursSinceBreak: 2,
      cycleHoursUsed: 40,
      allowDock: true,
      dockRest: { stopId: 'pu-1', truckParkedHours: 12, convertToRest: true },
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 1,
      hosCompliant: true,
      feasible: true,
      minTripHours: 7,
      maxTripHours: 15,
      notes: 'Dock rest resets HOS. Fresh 7h drive after',
    },
  ),
  sc(
    'S-045',
    'BR to Atlanta, 3h docks each',
    'medium',
    'batonRouge',
    'batonRouge',
    'atlanta',
    500,
    8,
    { pickupDock: 3, deliveryDock: 3 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 10,
      maxTripHours: 18,
      notes: '3h dock+8h drive+3h dock=14h duty. Break needed',
    },
  ),

  // Optimization priorities
  sc(
    'S-046',
    'KC to Chi, prefer full rest',
    'medium',
    'kansasCity',
    'kansasCity',
    'chicago',
    500,
    8,
    {
      deliveryDock: 2,
      hoursDriven: 5,
      onDutyTime: 6,
      hoursSinceBreak: 2,
      cycleHoursUsed: 30,
      rest: 'full',
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 17,
      maxTripHours: 25,
      notes: 'Full rest: drives then 10h rest then finishes',
    },
  ),
  sc(
    'S-047',
    'Dallas to Memphis, split 8/2',
    'medium',
    'dallas',
    'dallas',
    'memphis',
    450,
    7,
    {
      deliveryDock: 1.5,
      hoursDriven: 6,
      onDutyTime: 7,
      hoursSinceBreak: 1,
      cycleHoursUsed: 35,
      rest: 'split_8_2',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 2,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 16,
      maxTripHours: 24,
      notes: 'Split 8/2: first 8h then second 2h portions',
    },
  ),
  sc(
    'S-048',
    'Houston to Memphis, split 7/3',
    'medium',
    'houston',
    'houston',
    'memphis',
    580,
    9.5,
    {
      deliveryDock: 1.5,
      hoursDriven: 4,
      onDutyTime: 5,
      hoursSinceBreak: 2,
      cycleHoursUsed: 25,
      rest: 'split_7_3',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 2,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 19,
      maxTripHours: 27,
      notes: 'Split 7/3: first 7h then second 3h portions',
    },
  ),
  sc(
    'S-049',
    'Atlanta to Jax, auto rest with sleeper',
    'medium',
    'atlanta',
    'atlanta',
    'jacksonville',
    345,
    5.5,
    {
      deliveryDock: 2,
      hoursDriven: 7,
      onDutyTime: 8,
      hoursSinceBreak: 1,
      cycleHoursUsed: 40,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 15,
      maxTripHours: 23,
      notes: 'Auto mode: full rest for short remaining drive',
    },
  ),
  sc(
    'S-050',
    'Dallas to LR, no sleeper, full rest',
    'medium',
    'dallas',
    'dallas',
    'littleRock',
    320,
    5,
    {
      deliveryDock: 1.5,
      hoursDriven: 8,
      onDutyTime: 9,
      hoursSinceBreak: 2,
      cycleHoursUsed: 35,
      fuelCur: 120,
      hasSleeper: false,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 14,
      maxTripHours: 22,
      notes: 'No sleeper forces full_rest',
    },
  ),

  // ========= LONG ROUTES (S-051 to S-075) =========

  sc(
    'S-051',
    'Houston to Chi, auto 1050mi',
    'long',
    'houston',
    'houston',
    'chicago',
    1050,
    17,
    { pickupDock: 2, deliveryDock: 2, fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 29,
      maxTripHours: 43,
      notes: '17h drive, 2 duty periods. 1050/6.5=162>150cap',
    },
  ),
  sc(
    'S-052',
    'Houston to Chi, full rest 1050mi',
    'long',
    'houston',
    'houston',
    'chicago',
    1050,
    17,
    { pickupDock: 2, deliveryDock: 2, rest: 'full', fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 39,
      maxTripHours: 47,
      notes: 'Full rest takes longer than splits',
    },
  ),
  sc(
    'S-053',
    'Dallas to Chi, split 8/2 920mi',
    'long',
    'dallas',
    'dallas',
    'chicago',
    920,
    14.5,
    { deliveryDock: 2, rest: 'split_8_2', fuelAvail: 'multiple' },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 25,
      maxTripHours: 33,
      notes: 'Split 8/2: 920/6.5=141gal needs fuel',
    },
  ),
  sc(
    'S-054',
    'Houston to ATL, split 7/3 790mi',
    'long',
    'houston',
    'houston',
    'atlanta',
    790,
    12.5,
    {
      pickupDock: 1.5,
      deliveryDock: 2,
      rest: 'split_7_3',
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 24,
      maxTripHours: 32,
      notes: 'Split 7/3: 790/6.5=122gal needs fuel',
    },
  ),
  sc(
    'S-055',
    'Miami to ATL, no sleeper 660mi',
    'long',
    'miami',
    'miami',
    'atlanta',
    660,
    10.5,
    {
      pickupDock: 2,
      deliveryDock: 2,
      fuelCur: 130,
      mpg: 6,
      hasSleeper: false,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 0,
      maxRestStops: 1,
      minFuelStops: 3,
      minBreaks: 2,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 13,
      maxTripHours: 21,
      notes: 'No sleeper: 10.5h drive at limit. Fuel: 660/6=110gal',
    },
  ),

  sc(
    'S-056',
    'Dallas to Denver, low fuel 780mi',
    'long',
    'dallas',
    'dallas',
    'denver',
    780,
    12,
    { deliveryDock: 2, fuelCur: 60, mpg: 6, fuelAvail: 'multiple' },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 33,
      maxTripHours: 41,
      notes: '60gal start, 780/6=130gal needed',
    },
  ),
  sc(
    'S-057',
    'Chi to ATL, half tank 720mi',
    'long',
    'chicago',
    'chicago',
    'atlanta',
    720,
    11,
    { deliveryDock: 2, fuelCur: 75, mpg: 6, fuelAvail: 'multiple' },
    {
      minDriveSegments: 3,
      minRestStops: 1,
      maxRestStops: 2,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 22,
      maxTripHours: 30,
      notes: '75gal, 720/6=120gal. Near drive limit',
    },
  ),
  sc(
    'S-058',
    'OKC to Chi, 100gal tank 700mi',
    'long',
    'oklahomaCity',
    'oklahomaCity',
    'chicago',
    700,
    11,
    {
      deliveryDock: 2,
      fuelCap: 100,
      fuelCur: 90,
      mpg: 6,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 1,
      maxRestStops: 2,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 22,
      maxTripHours: 30,
      notes: 'Small tank: 700/6=117>100cap',
    },
  ),
  sc(
    'S-059',
    'Houston to ATL, near empty 790mi',
    'long',
    'houston',
    'houston',
    'atlanta',
    790,
    12.5,
    {
      pickupDock: 1.5,
      deliveryDock: 2,
      fuelCur: 55,
      mpg: 5.5,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 34,
      maxTripHours: 42,
      notes: '55gal start, 790/5.5=144gal needed',
    },
  ),
  sc(
    'S-060',
    'Dallas to Chi, 4.5mpg 920mi',
    'long',
    'dallas',
    'dallas',
    'chicago',
    920,
    14.5,
    { pickupDock: 2, deliveryDock: 2, mpg: 4.5, fuelAvail: 'multiple' },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 36,
      maxTripHours: 44,
      notes: 'Heavy: 920/4.5=204gal>150cap',
    },
  ),

  sc(
    'S-061',
    'Houston to ATL, 2-day 790mi',
    'long',
    'houston',
    'houston',
    'atlanta',
    790,
    12.5,
    {
      pickupDock: 2,
      deliveryDock: 2,
      fuelCur: 140,
      cycleHoursUsed: 10,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 34,
      maxTripHours: 42,
      notes: '12.5h drive across 2 duty periods',
    },
  ),
  sc(
    'S-062',
    'Dallas to Denver, 2-day 780mi',
    'long',
    'dallas',
    'dallas',
    'denver',
    780,
    12,
    {
      pickupDock: 1.5,
      deliveryDock: 2.5,
      fuelCur: 130,
      mpg: 6,
      cycleHoursUsed: 5,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 33,
      maxTripHours: 41,
      notes: '780/6=130gal. 2 periods',
    },
  ),
  sc(
    'S-063',
    'Dallas to Chi, snow 920mi',
    'long',
    'dallas',
    'dallas',
    'chicago',
    920,
    14.5,
    { deliveryDock: 2, weather: 'snow', fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 30,
      maxTripHours: 38,
      notes: 'Snow 1.3x: 18.85h effective drive',
    },
  ),
  sc(
    'S-064',
    'Memphis to Chi, tight single-day 530mi',
    'long',
    'memphis',
    'memphis',
    'chicago',
    530,
    8.5,
    { pickupDock: 1, deliveryDock: 1.5 },
    {
      minDriveSegments: 3,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 2,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 9,
      maxTripHours: 17,
      notes: '8.5h drive fits single day with breaks',
    },
  ),
  sc(
    'S-065',
    'Houston to Detroit, 3-period 1280mi',
    'long',
    'houston',
    'houston',
    'detroit',
    1280,
    20,
    { pickupDock: 2, deliveryDock: 2, mpg: 6, fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 42,
      maxTripHours: 50,
      notes: '20h drive: 3 duty periods. 1280/6=213gal',
    },
  ),

  sc(
    'S-066',
    'Dallas to Chi, 3h driven 920mi',
    'long',
    'dallas',
    'dallas',
    'chicago',
    920,
    14.5,
    {
      deliveryDock: 2,
      hoursDriven: 3,
      onDutyTime: 4,
      hoursSinceBreak: 4,
      cycleHoursUsed: 30,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 35,
      maxTripHours: 43,
      notes: '3h already driven. Multiple periods',
    },
  ),
  sc(
    'S-067',
    'Houston to ATL, 5h driven 790mi',
    'long',
    'houston',
    'houston',
    'atlanta',
    790,
    12.5,
    {
      deliveryDock: 2,
      hoursDriven: 5,
      onDutyTime: 6,
      hoursSinceBreak: 2,
      cycleHoursUsed: 35,
      fuelCur: 130,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 33,
      maxTripHours: 41,
      notes: '5h driven, first period shorter',
    },
  ),
  sc(
    'S-068',
    'Miami to ATL, 8h driven 660mi',
    'long',
    'miami',
    'miami',
    'atlanta',
    660,
    10.5,
    {
      deliveryDock: 2,
      hoursDriven: 8,
      onDutyTime: 9,
      hoursSinceBreak: 1,
      cycleHoursUsed: 45,
      fuelCur: 120,
      mpg: 6,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 1,
      maxRestStops: 2,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 22,
      maxTripHours: 30,
      notes: 'Only 3h drive left first period',
    },
  ),
  sc(
    'S-069',
    'Dallas to Denver, 55h cycle 780mi',
    'long',
    'dallas',
    'dallas',
    'denver',
    780,
    12,
    {
      deliveryDock: 2,
      cycleHoursUsed: 55,
      fuelCur: 140,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 33,
      maxTripHours: 41,
      notes: '55h cycle used, 15h remaining',
    },
  ),
  sc(
    'S-070',
    'Chi to ATL, break taken 720mi',
    'long',
    'chicago',
    'chicago',
    'atlanta',
    720,
    11,
    {
      deliveryDock: 2,
      hoursDriven: 6,
      onDutyTime: 7,
      hoursSinceBreak: 0,
      cycleHoursUsed: 40,
      fuelCur: 130,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 1,
      maxRestStops: 2,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 22,
      maxTripHours: 30,
      notes: '6h driven, hoursSinceBreak=0',
    },
  ),

  sc(
    'S-071',
    'Houston to Chi, combined 1050mi',
    'long',
    'houston',
    'houston',
    'chicago',
    1050,
    17,
    {
      pickupDock: 1.5,
      deliveryDock: 2,
      fuelCur: 100,
      mpg: 6,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 4,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 29,
      maxTripHours: 37,
      notes: 'Fuel+rest at same stops',
    },
  ),
  sc(
    'S-072',
    'Dallas to Denver, fuel+rest 780mi',
    'long',
    'dallas',
    'dallas',
    'denver',
    780,
    12,
    {
      deliveryDock: 2,
      fuelCur: 80,
      mpg: 5.5,
      cycleHoursUsed: 10,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 33,
      maxTripHours: 41,
      notes: '780/5.5=142gal, fuel+rest co-located',
    },
  ),
  sc(
    'S-073',
    'Houston to ATL, rain+fuel 790mi',
    'long',
    'houston',
    'houston',
    'atlanta',
    790,
    12.5,
    {
      deliveryDock: 1.5,
      fuelCur: 90,
      mpg: 6,
      cycleHoursUsed: 20,
      weather: 'rain',
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 2,
      maxRestStops: 3,
      minFuelStops: 3,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 34,
      maxTripHours: 42,
      notes: 'Rain 1.1x: 13.75h drive. Fuel+rest',
    },
  ),
  sc(
    'S-074',
    'Miami to ATL, both needed 660mi',
    'long',
    'miami',
    'miami',
    'atlanta',
    660,
    10.5,
    {
      deliveryDock: 2,
      hoursDriven: 4,
      onDutyTime: 5,
      hoursSinceBreak: 5,
      cycleHoursUsed: 25,
      fuelCur: 70,
      mpg: 5.5,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 3,
      minRestStops: 1,
      maxRestStops: 2,
      minFuelStops: 3,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 22,
      maxTripHours: 30,
      notes: '4h driven. Fuel+rest both needed',
    },
  ),
  sc(
    'S-075',
    'Dallas to Chi, ice+fuel 920mi',
    'long',
    'dallas',
    'dallas',
    'chicago',
    920,
    14.5,
    {
      deliveryDock: 2,
      fuelCur: 80,
      mpg: 5.5,
      weather: 'ice',
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 43,
      maxTripHours: 51,
      notes: 'Ice 1.5x: 21.75h! Multiple periods',
    },
  ),

  // ========= CROSS-COUNTRY (S-076 to S-090) =========

  sc(
    'S-076',
    'Houston to NYC 1630mi',
    'cross-country',
    'houston',
    'houston',
    'newYork',
    1630,
    26,
    { pickupDock: 2, deliveryDock: 2, fuelAvail: 'multiple' },
    {
      minDriveSegments: 5,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 49,
      maxTripHours: 57,
      notes: '26h drive: 3 duty periods. 1630/6.5=251gal',
    },
  ),
  sc(
    'S-077',
    'Laredo to Chi 1350mi',
    'cross-country',
    'laredo',
    'laredo',
    'chicago',
    1350,
    22,
    { pickupDock: 3, deliveryDock: 2, mpg: 6, fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 45,
      maxTripHours: 53,
      notes: '22h drive, 3h customs dock',
    },
  ),
  sc(
    'S-078',
    'LA to Dallas 1440mi',
    'cross-country',
    'losAngeles',
    'losAngeles',
    'dallas',
    1440,
    22,
    { pickupDock: 2, deliveryDock: 2, fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 44,
      maxTripHours: 52,
      notes: '22h drive. 1440/6.5=222gal',
    },
  ),
  sc(
    'S-079',
    'Miami to Chi 1380mi',
    'cross-country',
    'miami',
    'miami',
    'chicago',
    1380,
    22,
    { pickupDock: 1.5, deliveryDock: 2, fuelCur: 140, fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 44,
      maxTripHours: 52,
      notes: '22h drive. 1380/6.5=212gal',
    },
  ),
  sc(
    'S-080',
    'Denver to ATL 1400mi',
    'cross-country',
    'denver',
    'denver',
    'atlanta',
    1400,
    22,
    { deliveryDock: 2, mpg: 6, fuelAvail: 'multiple' },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 43,
      maxTripHours: 51,
      notes: '22h drive. 1400/6=233gal',
    },
  ),

  sc(
    'S-081',
    'Houston to NYC, 5h driven',
    'cross-country',
    'houston',
    'houston',
    'newYork',
    1630,
    26,
    {
      deliveryDock: 2,
      hoursDriven: 5,
      onDutyTime: 6,
      hoursSinceBreak: 2,
      cycleHoursUsed: 30,
      fuelCur: 130,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 5,
      minRestStops: 4,
      maxRestStops: 5,
      minFuelStops: 5,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 58,
      maxTripHours: 66,
      notes: '5h driven, 26h more. 4+ periods',
    },
  ),
  sc(
    'S-082',
    'Laredo to Chi, 8h driven',
    'cross-country',
    'laredo',
    'laredo',
    'chicago',
    1350,
    22,
    {
      deliveryDock: 2,
      hoursDriven: 8,
      onDutyTime: 9,
      hoursSinceBreak: 1,
      cycleHoursUsed: 40,
      fuelCur: 120,
      mpg: 6,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 5,
      minRestStops: 4,
      maxRestStops: 5,
      minFuelStops: 5,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 54,
      maxTripHours: 62,
      notes: 'Only 3h first period. 4+ periods',
    },
  ),
  sc(
    'S-083',
    'LA to Dallas, 10h driven',
    'cross-country',
    'losAngeles',
    'losAngeles',
    'dallas',
    1440,
    22,
    {
      deliveryDock: 2,
      hoursDriven: 10,
      onDutyTime: 12,
      hoursSinceBreak: 2,
      cycleHoursUsed: 45,
      fuelCur: 140,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 6,
      minRestStops: 5,
      maxRestStops: 6,
      minFuelStops: 5,
      minBreaks: 0,
      needsRestart: true,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 88,
      maxTripHours: 96,
      notes: '1h left first period. Many rest cycles. Cycle restart triggered',
    },
  ),
  sc(
    'S-084',
    'Miami to Chi, 6h driven 50h cycle',
    'cross-country',
    'miami',
    'miami',
    'chicago',
    1380,
    22,
    {
      deliveryDock: 2,
      hoursDriven: 6,
      onDutyTime: 7,
      hoursSinceBreak: 3,
      cycleHoursUsed: 50,
      fuelCur: 130,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 5,
      minRestStops: 4,
      maxRestStops: 5,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: true,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 77,
      maxTripHours: 85,
      notes: '50h cycle+22h drive triggers restart',
    },
  ),
  sc(
    'S-085',
    'Denver to ATL, 3h driven 35h cycle',
    'cross-country',
    'denver',
    'denver',
    'atlanta',
    1400,
    22,
    {
      deliveryDock: 2,
      hoursDriven: 3,
      onDutyTime: 4,
      hoursSinceBreak: 4,
      cycleHoursUsed: 35,
      mpg: 6,
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 43,
      maxTripHours: 51,
      notes: '35h cycle, 22h drive. Fits without restart',
    },
  ),

  sc(
    'S-086',
    'Houston to NYC, ice 1630mi',
    'cross-country',
    'houston',
    'houston',
    'newYork',
    1630,
    26,
    { deliveryDock: 2, weather: 'ice', fuelAvail: 'multiple' },
    {
      minDriveSegments: 7,
      minRestStops: 6,
      maxRestStops: 7,
      minFuelStops: 6,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 81,
      maxTripHours: 89,
      notes: 'Ice 1.5x: 39h drive! 4 duty periods',
    },
  ),
  sc(
    'S-087',
    'Laredo to Chi, snow 1350mi',
    'cross-country',
    'laredo',
    'laredo',
    'chicago',
    1350,
    22,
    { deliveryDock: 2, mpg: 6, weather: 'snow', fuelAvail: 'multiple' },
    {
      minDriveSegments: 5,
      minRestStops: 4,
      maxRestStops: 5,
      minFuelStops: 5,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 60,
      maxTripHours: 68,
      notes: 'Snow 1.3x: 28.6h drive. 3 duty periods',
    },
  ),
  sc(
    'S-088',
    'LA to Dallas, thunderstorm 1440mi',
    'cross-country',
    'losAngeles',
    'losAngeles',
    'dallas',
    1440,
    22,
    { deliveryDock: 2, weather: 'thunderstorm', fuelAvail: 'multiple' },
    {
      minDriveSegments: 5,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 48,
      maxTripHours: 56,
      notes: 'Thunderstorm 1.2x: 26.4h drive',
    },
  ),
  sc(
    'S-089',
    'Miami to Chi, rain+low fuel 1380mi',
    'cross-country',
    'miami',
    'miami',
    'chicago',
    1380,
    22,
    {
      deliveryDock: 2,
      fuelCur: 60,
      mpg: 5.5,
      weather: 'rain',
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 5,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 4,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 46,
      maxTripHours: 54,
      notes: 'Rain 1.1x. 60gal start, 1380/5.5=251gal',
    },
  ),
  sc(
    'S-090',
    'Denver to ATL, snow+5h HOS 1400mi',
    'cross-country',
    'denver',
    'denver',
    'atlanta',
    1400,
    22,
    {
      deliveryDock: 2,
      hoursDriven: 5,
      onDutyTime: 6,
      hoursSinceBreak: 2,
      cycleHoursUsed: 30,
      fuelCur: 140,
      mpg: 6,
      weather: 'snow',
      fuelAvail: 'multiple',
    },
    {
      minDriveSegments: 5,
      minRestStops: 4,
      maxRestStops: 5,
      minFuelStops: 5,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 60,
      maxTripHours: 68,
      notes: 'Snow 1.3x: 28.6h + 5h already driven',
    },
  ),

  // ========= EDGE CASES (S-091 to S-105) =========

  sc(
    'S-091',
    '70h cycle exhausted, 34h restart',
    'edge',
    'houston',
    'houston',
    'dallas',
    240,
    3.75,
    { deliveryDock: 1.5, cycleHoursUsed: 70, fuelCur: 120 },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: true,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: '70h cycle: 34h restart. tripHours excludes rest idle time',
    },
  ),
  sc(
    'S-092',
    '69.5h cycle, restart triggered',
    'edge',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    { deliveryDock: 1, cycleHoursUsed: 69.5, fuelCur: 120 },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: true,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 37,
      maxTripHours: 45,
      notes: '69.5h+dock pushes over 70h. 34h restart',
    },
  ),
  sc(
    'S-093',
    '11h driven, cannot drive',
    'edge',
    'memphis',
    'memphis',
    'nashville',
    210,
    3.5,
    {
      pickupDock: 0.5,
      deliveryDock: 1,
      hoursDriven: 11,
      onDutyTime: 12,
      hoursSinceBreak: 1,
      cycleHoursUsed: 50,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: '0h remaining. Full rest first',
    },
  ),
  sc(
    'S-094',
    '14h duty hit, only 8h driven',
    'edge',
    'atlanta',
    'atlanta',
    'birmingham',
    150,
    2.5,
    {
      pickupDock: 0.5,
      deliveryDock: 1,
      hoursDriven: 8,
      onDutyTime: 14,
      hoursSinceBreak: 1,
      cycleHoursUsed: 50,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 1,
      maxTripHours: 9,
      notes: 'Duty window closed. Rest then short drive',
    },
  ),
  sc(
    'S-095',
    'Break clock at 8h, must break',
    'edge',
    'chicago',
    'chicago',
    'indianapolis',
    185,
    3,
    {
      pickupDock: 0.5,
      deliveryDock: 1,
      hoursDriven: 3,
      onDutyTime: 8,
      hoursSinceBreak: 8,
      cycleHoursUsed: 30,
      fuelCur: 120,
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: '8h since break, immediate break',
    },
  ),
  sc(
    'S-096',
    'Empty tank, immediate fuel',
    'edge',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    { deliveryDock: 1, fuelCur: 0, fuelAvail: 'multiple' },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 1,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: '0 gal fuel, must fuel immediately',
    },
  ),
  sc(
    'S-097',
    'No sleeper, needs rest, full only',
    'edge',
    'memphis',
    'memphis',
    'chicago',
    530,
    8.5,
    {
      deliveryDock: 2,
      hoursDriven: 6,
      onDutyTime: 7,
      hoursSinceBreak: 1,
      cycleHoursUsed: 35,
      fuelCur: 120,
      mpg: 6,
      hasSleeper: false,
      rest: 'split_8_2',
    },
    {
      minDriveSegments: 3,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 1,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 18,
      maxTripHours: 26,
      notes: 'Split requested but no sleeper, falls back to full_rest',
    },
  ),
  sc(
    'S-098',
    'Dock 9.5h, NOT qualifying rest',
    'edge',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    {
      deliveryDock: 2,
      hoursDriven: 9,
      onDutyTime: 11,
      hoursSinceBreak: 3,
      cycleHoursUsed: 40,
      fuelCur: 120,
      allowDock: true,
      dockRest: { stopId: 'pu-1', truckParkedHours: 9.5, convertToRest: true },
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 13,
      maxTripHours: 21,
      notes: '9.5h<10h minimum. Does NOT qualify',
    },
  ),
  sc(
    'S-099',
    'Dock 10h exactly, qualifies as rest',
    'edge',
    'houston',
    'houston',
    'austin',
    165,
    2.75,
    {
      deliveryDock: 2,
      hoursDriven: 9,
      onDutyTime: 11,
      hoursSinceBreak: 3,
      cycleHoursUsed: 40,
      fuelCur: 120,
      allowDock: true,
      dockRest: { stopId: 'pu-1', truckParkedHours: 10, convertToRest: true },
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 1,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: '10h dock qualifies. HOS resets',
    },
  ),
  sc(
    'S-100',
    'All clocks near limit simultaneously',
    'edge',
    'houston',
    'houston',
    'dallas',
    240,
    3.75,
    {
      pickupDock: 0.5,
      deliveryDock: 1,
      hoursDriven: 10,
      onDutyTime: 13,
      hoursSinceBreak: 7.5,
      cycleHoursUsed: 68,
      fuelCur: 120,
    },
    {
      minDriveSegments: 4,
      minRestStops: 3,
      maxRestStops: 4,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: true,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 56,
      maxTripHours: 64,
      notes: 'All limits hit. Multiple rests including restart',
    },
  ),

  sc(
    'S-101',
    'Zero-distance origin to pickup',
    'edge',
    'houston',
    'houston',
    'sanAntonio',
    200,
    3.25,
    { deliveryDock: 1 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 2,
      maxTripHours: 10,
      notes: 'Same city origin/pickup. Short drive',
    },
  ),
  sc(
    'S-102',
    'Very short hop, huge docks',
    'edge',
    'philadelphia',
    'philadelphia',
    'newYork',
    100,
    2,
    { pickupDock: 6, deliveryDock: 6 },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 7,
      maxTripHours: 15,
      notes: '6h+6h docks but only 2h DRIVING — no break required; docks do not count (FMCSA §395.3)',
    },
  ),
  sc(
    'S-103',
    'Fresh driver max single-day',
    'edge',
    'memphis',
    'memphis',
    'chicago',
    530,
    8.5,
    { pickupDock: 0.5, deliveryDock: 0.5 },
    {
      minDriveSegments: 3,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 2,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 8,
      maxTripHours: 16,
      notes: '8.5h drive with breaks. Splits near HOS limit',
    },
  ),
  sc(
    'S-104',
    'Weather + near duty limit',
    'edge',
    'nashville',
    'nashville',
    'atlanta',
    250,
    4,
    {
      deliveryDock: 1,
      hoursDriven: 5,
      onDutyTime: 10,
      hoursSinceBreak: 2,
      cycleHoursUsed: 40,
      fuelCur: 120,
      weather: 'ice',
    },
    {
      minDriveSegments: 2,
      minRestStops: 1,
      maxRestStops: 1,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 15,
      maxTripHours: 23,
      notes: 'Ice 1.5x: 6h drive. Only 3h duty left. Rest mid-route',
    },
  ),
  sc(
    'S-105',
    'Split sleeper, no rest needed',
    'edge',
    'dallas',
    'dallas',
    'houston',
    240,
    3.75,
    {
      deliveryDock: 1,
      hoursDriven: 6,
      onDutyTime: 7,
      hoursSinceBreak: 0,
      cycleHoursUsed: 35,
      fuelCur: 120,
      rest: 'split_8_2',
    },
    {
      minDriveSegments: 2,
      minRestStops: 0,
      maxRestStops: 0,
      minFuelStops: 0,
      minBreaks: 0,
      needsRestart: false,
      dockRestConversions: 0,
      hosCompliant: true,
      feasible: true,
      minTripHours: 3,
      maxTripHours: 11,
      notes: '6h driven but 5h drive+7h duty left. No rest needed',
    },
  ),
];
