/**
 * SALLY RBAC Permission Matrix — AUTO-GENERATED
 *
 * DO NOT EDIT MANUALLY. Regenerate with:
 *   npx tsx scripts/generate-rbac-matrix.ts --write
 *
 * Generated: 2026-04-17T08:31:25.838Z
 * Source: 0 domains, 229 endpoints
 * Controllers scanned: 629 total endpoints across all controllers
 *
 * Status codes:
 *   200      = allowed (request succeeds)
 *   403      = forbidden (role not permitted). Test also accepts 404.
 *   null     = skip (needs entity ID or tested in workflows)
 */

export interface RbacEntry {
  method: string;
  path: string;
  description: string;
  domain: string;
  featureGate: string | null;
  expectations: Record<string, number | null>;
}

export const RBAC_MATRIX: RbacEntry[] = [

  // ═══════════════════════════════════════════════════════
  // INFRASTRUCTURE
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/admin/platform-services/health',
    description: 'PlatformHealthController: GET /admin/platform-services/health',
    domain: 'infrastructure',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/auth/me',
    description: 'AuthController: GET /auth/me',
    domain: 'infrastructure',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/health/live',
    description: 'HealthController: GET /health/live',
    domain: 'infrastructure',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/health/ready',
    description: 'HealthController: GET /health/ready',
    domain: 'infrastructure',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },

  // ═══════════════════════════════════════════════════════
  // SUPER-ADMIN
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/admin/events',
    description: 'AdminEventsController: GET /admin/events',
    domain: 'super-admin',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/events/stats',
    description: 'AdminEventsController: GET /admin/events/stats',
    domain: 'super-admin',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/events/volume',
    description: 'AdminEventsController: GET /admin/events/volume',
    domain: 'super-admin',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/events/webhooks/health',
    description: 'AdminEventsController: GET /admin/events/webhooks/health',
    domain: 'super-admin',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/jobs',
    description: 'AdminJobsController: GET /admin/jobs',
    domain: 'super-admin',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/schedules',
    description: 'AdminSchedulesController: GET /admin/schedules',
    domain: 'super-admin',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },

  // ═══════════════════════════════════════════════════════
  // AI
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/ai/documents/parser-config',
    description: 'RateconController: GET /ai/documents/parser-config',
    domain: 'ai',
    featureGate: 'doc_intelligence',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/jobs',
    description: 'JobsController: GET /jobs',
    domain: 'ai',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/jobs/categories/summary',
    description: 'JobsController: GET /jobs/categories/summary',
    domain: 'ai',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/ai/documents/parse-ratecon',
    description: 'RateconController: POST /ai/documents/parse-ratecon',
    domain: 'ai',
    featureGate: 'doc_intelligence',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/ai/documents/parse-ratecon/bulk',
    description: 'RateconController: POST /ai/documents/parse-ratecon/bulk',
    domain: 'ai',
    featureGate: 'doc_intelligence',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/ifta/fuel-receipts/scan',
    description: 'FuelReceiptController: POST /ifta/fuel-receipts/scan',
    domain: 'ai',
    featureGate: 'ifta',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: null, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },

  // ═══════════════════════════════════════════════════════
  // OTHER
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/analytics/kpi',
    description: 'AnalyticsController: GET /analytics/kpi',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/analytics/reports/ar-aging',
    description: 'AnalyticsController: GET /analytics/reports/ar-aging',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/analytics/reports/customers',
    description: 'AnalyticsController: GET /analytics/reports/customers',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/analytics/reports/drivers',
    description: 'AnalyticsController: GET /analytics/reports/drivers',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/analytics/reports/fleet',
    description: 'AnalyticsController: GET /analytics/reports/fleet',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/analytics/reports/lanes',
    description: 'AnalyticsController: GET /analytics/reports/lanes',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/analytics/reports/profitability',
    description: 'AnalyticsController: GET /analytics/reports/profitability',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/analytics/reports/revenue',
    description: 'AnalyticsController: GET /analytics/reports/revenue',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/desk/agents',
    description: 'DeskAgentController: GET /desk/agents',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/desk/episodes',
    description: 'DeskController: GET /desk/episodes',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/desk/healthcheck',
    description: 'DeskController: GET /desk/healthcheck',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/desk/responsibilities',
    description: 'DeskController: GET /desk/responsibilities',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/desk/review-items',
    description: 'DeskReviewController: GET /desk/review-items',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/fuel-cards/admin/brand-acceptance',
    description: 'FuelCardsController: GET /fuel-cards/admin/brand-acceptance',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/fuel-cards/admin/types',
    description: 'FuelCardsController: GET /fuel-cards/admin/types',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/fuel-cards/types',
    description: 'FuelCardsController: GET /fuel-cards/types',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/home/pulse',
    description: 'HomeController: GET /home/pulse',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/home/recent-loads',
    description: 'HomeController: GET /home/recent-loads',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/push/vapid-key',
    description: 'PushSubscriptionController: GET /push/vapid-key',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/webhooks',
    description: 'SubscriptionController: GET /webhooks',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/webhooks/events',
    description: 'SubscriptionController: GET /webhooks/events',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/fuel-cards/admin/brand-acceptance',
    description: 'FuelCardsController: POST /fuel-cards/admin/brand-acceptance',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: null },
  },
  {
    method: 'POST', path: '/webhooks',
    description: 'SubscriptionController: POST /webhooks',
    domain: 'other',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },

  // ═══════════════════════════════════════════════════════
  // FINANCIALS
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/admin/billing/revenue',
    description: 'BillingAdminController: GET /admin/billing/revenue',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/billing/invoices',
    description: 'BillingController: GET /billing/invoices',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/billing/overview',
    description: 'BillingController: GET /billing/overview',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/billing/payment-methods',
    description: 'BillingController: GET /billing/payment-methods',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/billing/wallet',
    description: 'BillingController: GET /billing/wallet',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/billing/wallet/transactions',
    description: 'BillingController: GET /billing/wallet/transactions',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/close-out',
    description: 'CloseOutController: GET /close-out',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/close-out/summary',
    description: 'CloseOutController: GET /close-out/summary',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/invoices',
    description: 'InvoicingController: GET /invoices',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/invoices/factoring-companies',
    description: 'InvoicingController: GET /invoices/factoring-companies',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/invoices/noa-records',
    description: 'InvoicingController: GET /invoices/noa-records',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/invoices/settings',
    description: 'InvoicingController: GET /invoices/settings',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/invoices/summary',
    description: 'InvoicingController: GET /invoices/summary',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/pay-structures/mine',
    description: 'PayStructureController: GET /pay-structures/mine',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/profitability/loads',
    description: 'ProfitabilityController: GET /profitability/loads',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/settlements',
    description: 'SettlementsController: GET /settlements',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/settlements/my-settlements',
    description: 'SettlementsController: GET /settlements/my-settlements',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/settlements/summary',
    description: 'SettlementsController: GET /settlements/summary',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/billing/cancel',
    description: 'BillingController: POST /billing/cancel',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/billing/checkout',
    description: 'BillingController: POST /billing/checkout',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/billing/downgrade',
    description: 'BillingController: POST /billing/downgrade',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/billing/payment-methods/setup',
    description: 'BillingController: POST /billing/payment-methods/setup',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PATCH', path: '/billing/quantity',
    description: 'BillingController: PATCH /billing/quantity',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/billing/reactivate',
    description: 'BillingController: POST /billing/reactivate',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/billing/upgrade',
    description: 'BillingController: POST /billing/upgrade',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PATCH', path: '/billing/wallet/auto-reload',
    description: 'BillingController: PATCH /billing/wallet/auto-reload',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/billing/wallet/top-up',
    description: 'BillingController: POST /billing/wallet/top-up',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices',
    description: 'InvoicingController: POST /invoices',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/batch/download',
    description: 'InvoicingController: POST /invoices/batch/download',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/batch/factor',
    description: 'InvoicingController: POST /invoices/batch/factor',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/batch/generate',
    description: 'InvoicingController: POST /invoices/batch/generate',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/batch/mark-paid',
    description: 'InvoicingController: POST /invoices/batch/mark-paid',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/batch/send',
    description: 'InvoicingController: POST /invoices/batch/send',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/batch/submit-to-factor',
    description: 'InvoicingController: POST /invoices/batch/submit-to-factor',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/batch/void',
    description: 'InvoicingController: POST /invoices/batch/void',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/factoring-companies',
    description: 'InvoicingController: POST /invoices/factoring-companies',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invoices/noa-records',
    description: 'InvoicingController: POST /invoices/noa-records',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PATCH', path: '/invoices/settings',
    description: 'InvoicingController: PATCH /invoices/settings',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settlements/batch-approve',
    description: 'SettlementsController: POST /settlements/batch-approve',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settlements/batch-calculate',
    description: 'SettlementsController: POST /settlements/batch-calculate',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settlements/batch-pay',
    description: 'SettlementsController: POST /settlements/batch-pay',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settlements/batch-pdf',
    description: 'SettlementsController: POST /settlements/batch-pdf',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settlements/batch-void',
    description: 'SettlementsController: POST /settlements/batch-void',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settlements/calculate',
    description: 'SettlementsController: POST /settlements/calculate',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settlements/preview-batch',
    description: 'SettlementsController: POST /settlements/preview-batch',
    domain: 'financials',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },

  // ═══════════════════════════════════════════════════════
  // FLEET
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/convoys',
    description: 'ConvoyController: GET /convoys',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/custom-fields/definitions',
    description: 'CustomFieldsController: GET /custom-fields/definitions',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/customer/loads',
    description: 'CustomerLoadsController: GET /customer/loads',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 200, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/customers',
    description: 'CustomersController: GET /customers',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/driver/sally/timeline',
    description: 'DriverTimelineController: GET /driver/sally/timeline',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/drivers',
    description: 'DriversController: GET /drivers',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/drivers/dispatch-board',
    description: 'DriversController: GET /drivers/dispatch-board',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/drivers/inactive/list',
    description: 'DriversController: GET /drivers/inactive/list',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/drivers/pending/list',
    description: 'DriversController: GET /drivers/pending/list',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/fleet/lane-rate',
    description: 'LaneIntelligenceController: GET /fleet/lane-rate',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/fleet/lane-rate-targets',
    description: 'LaneIntelligenceController: GET /fleet/lane-rate-targets',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/loads',
    description: 'LoadsController: GET /loads',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/recurring-lanes',
    description: 'RecurringLanesController: GET /recurring-lanes',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/recurring-lanes/upcoming',
    description: 'RecurringLanesController: GET /recurring-lanes/upcoming',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/stops',
    description: 'StopsController: GET /stops',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/stops/search',
    description: 'StopsController: GET /stops/search',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/trailers',
    description: 'TrailersController: GET /trailers',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/trailers/inactive/list',
    description: 'TrailersController: GET /trailers/inactive/list',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/vehicles',
    description: 'VehiclesController: GET /vehicles',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/vehicles/inactive/list',
    description: 'VehiclesController: GET /vehicles/inactive/list',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/convoys',
    description: 'ConvoyController: POST /convoys',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/custom-fields/definitions',
    description: 'CustomFieldsController: POST /custom-fields/definitions',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PATCH', path: '/custom-fields/definitions/reorder',
    description: 'CustomFieldsController: PATCH /custom-fields/definitions/reorder',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/customer/loads/request',
    description: 'CustomerLoadsController: POST /customer/loads/request',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: null, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/customers',
    description: 'CustomersController: POST /customers',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/documents/presign-upload',
    description: 'DocumentsController: POST /documents/presign-upload',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: null, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/drivers',
    description: 'DriversController: POST /drivers',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PUT', path: '/fleet/lane-rate-targets',
    description: 'LaneIntelligenceController: PUT /fleet/lane-rate-targets',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/loads',
    description: 'LoadsController: POST /loads',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/recurring-lanes',
    description: 'RecurringLanesController: POST /recurring-lanes',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/stops',
    description: 'StopsController: POST /stops',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/trailers',
    description: 'TrailersController: POST /trailers',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/vehicles',
    description: 'VehiclesController: POST /vehicles',
    domain: 'fleet',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },

  // ═══════════════════════════════════════════════════════
  // INTEGRATIONS
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/accounting/account-mappings',
    description: 'AccountingController: GET /accounting/account-mappings',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/accounting/status',
    description: 'AccountingController: GET /accounting/status',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/api/v1/integrations/eld/drivers',
    description: 'EldLinkingController: GET /api/v1/integrations/eld/drivers',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/api/v1/integrations/eld/vehicles',
    description: 'EldLinkingController: GET /api/v1/integrations/eld/vehicles',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/edi/settings/messages',
    description: 'EDISettingsController: GET /edi/settings/messages',
    domain: 'integrations',
    featureGate: 'edi_integration',
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/edi/settings/partners',
    description: 'EDISettingsController: GET /edi/settings/partners',
    domain: 'integrations',
    featureGate: 'edi_integration',
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/edi/tenders',
    description: 'EDITenderController: GET /edi/tenders',
    domain: 'integrations',
    featureGate: 'edi_integration',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/edi/tenders/rules',
    description: 'EDITenderController: GET /edi/tenders/rules',
    domain: 'integrations',
    featureGate: 'edi_integration',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/integrations',
    description: 'IntegrationsController: GET /integrations',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/integrations/email-intake/settings',
    description: 'EmailIntakeSettingsController: GET /integrations/email-intake/settings',
    domain: 'integrations',
    featureGate: 'email_intake',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/integrations/email-intake/threads',
    description: 'EmailIntakeController: GET /integrations/email-intake/threads',
    domain: 'integrations',
    featureGate: 'email_intake',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/integrations/health',
    description: 'IntegrationsController: GET /integrations/health',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/integrations/sync-history',
    description: 'IntegrationsController: GET /integrations/sync-history',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/integrations/vendors',
    description: 'IntegrationsController: GET /integrations/vendors',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/load-board/recommendations',
    description: 'LoadBoardController: GET /load-board/recommendations',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/load-board/saved-searches',
    description: 'LoadBoardController: GET /load-board/saved-searches',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/load-board/search-history',
    description: 'LoadBoardController: GET /load-board/search-history',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/accounting/setup/initial-sync',
    description: 'AccountingController: POST /accounting/setup/initial-sync',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/edi/settings/partners',
    description: 'EDISettingsController: POST /edi/settings/partners',
    domain: 'integrations',
    featureGate: 'edi_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/edi/tenders/rules',
    description: 'EDITenderController: POST /edi/tenders/rules',
    domain: 'integrations',
    featureGate: 'edi_integration',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations',
    description: 'IntegrationsController: POST /integrations',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations/eld/sync',
    description: 'IntegrationsController: POST /integrations/eld/sync',
    domain: 'integrations',
    featureGate: 'samsara_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations/eld/sync-hos',
    description: 'IntegrationsController: POST /integrations/eld/sync-hos',
    domain: 'integrations',
    featureGate: 'samsara_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations/eld/sync-telematics',
    description: 'IntegrationsController: POST /integrations/eld/sync-telematics',
    domain: 'integrations',
    featureGate: 'samsara_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations/fleet/sync',
    description: 'IntegrationsController: POST /integrations/fleet/sync',
    domain: 'integrations',
    featureGate: 'tms_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations/fleet/sync-drivers',
    description: 'IntegrationsController: POST /integrations/fleet/sync-drivers',
    domain: 'integrations',
    featureGate: 'tms_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations/fleet/sync-loads',
    description: 'IntegrationsController: POST /integrations/fleet/sync-loads',
    domain: 'integrations',
    featureGate: 'tms_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/integrations/fleet/sync-vehicles',
    description: 'IntegrationsController: POST /integrations/fleet/sync-vehicles',
    domain: 'integrations',
    featureGate: 'tms_integration',
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/load-board/import',
    description: 'LoadBoardController: POST /load-board/import',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/load-board/saved-searches',
    description: 'LoadBoardController: POST /load-board/saved-searches',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/load-board/search',
    description: 'LoadBoardController: POST /load-board/search',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/load-board/search/nlp',
    description: 'LoadBoardController: POST /load-board/search/nlp',
    domain: 'integrations',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },

  // ═══════════════════════════════════════════════════════
  // OPERATIONS
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/alerts',
    description: 'AlertsController: GET /alerts',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/analytics/resolution',
    description: 'AlertsController: GET /alerts/analytics/resolution',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/analytics/response-time',
    description: 'AlertsController: GET /alerts/analytics/response-time',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/analytics/top-types',
    description: 'AlertsController: GET /alerts/analytics/top-types',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/analytics/volume',
    description: 'AlertsController: GET /alerts/analytics/volume',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/grouped',
    description: 'AlertsController: GET /alerts/grouped',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/history',
    description: 'AlertsController: GET /alerts/history',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/stats',
    description: 'AlertsController: GET /alerts/stats',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/alerts/stats/smart',
    description: 'AlertsController: GET /alerts/stats/smart',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/command-center/map-data',
    description: 'CommandCenterController: GET /command-center/map-data',
    domain: 'operations',
    featureGate: 'command_center',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/command-center/message-summary',
    description: 'CommandCenterController: GET /command-center/message-summary',
    domain: 'operations',
    featureGate: 'command_center',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/command-center/overview',
    description: 'CommandCenterController: GET /command-center/overview',
    domain: 'operations',
    featureGate: 'command_center',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/command-center/shift-notes',
    description: 'CommandCenterController: GET /command-center/shift-notes',
    domain: 'operations',
    featureGate: 'command_center',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/command-center/system-health',
    description: 'CommandCenterController: GET /command-center/system-health',
    domain: 'operations',
    featureGate: 'command_center',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/horizon',
    description: 'HorizonController: GET /horizon',
    domain: 'operations',
    featureGate: 'horizon',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/ifta/quarters',
    description: 'IftaController: GET /ifta/quarters',
    domain: 'operations',
    featureGate: 'ifta',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/ifta/tax-rates',
    description: 'IftaController: GET /ifta/tax-rates',
    domain: 'operations',
    featureGate: 'ifta',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/notifications',
    description: 'NotificationsController: GET /notifications',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/notifications/count',
    description: 'NotificationsController: GET /notifications/count',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/routes',
    description: 'RoutePlanningController: GET /routes',
    domain: 'operations',
    featureGate: 'route_planning',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/shield',
    description: 'ShieldController: GET /shield',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/shield/audits',
    description: 'ShieldController: GET /shield/audits',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/shield/findings',
    description: 'ShieldController: GET /shield/findings',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/shield/rules',
    description: 'ShieldController: GET /shield/rules',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/shield/score',
    description: 'ShieldController: GET /shield/score',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/support/admin/stats',
    description: 'SupportController: GET /support/admin/stats',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/support/admin/tenants',
    description: 'SupportController: GET /support/admin/tenants',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/support/admin/tickets',
    description: 'SupportController: GET /support/admin/tickets',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/support/tickets',
    description: 'SupportController: GET /support/tickets',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/alerts/bulk/acknowledge',
    description: 'AlertsController: POST /alerts/bulk/acknowledge',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/alerts/bulk/resolve',
    description: 'AlertsController: POST /alerts/bulk/resolve',
    domain: 'operations',
    featureGate: 'alerts',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/command-center/shift-notes',
    description: 'CommandCenterController: POST /command-center/shift-notes',
    domain: 'operations',
    featureGate: 'command_center',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PATCH', path: '/command-center/shift-notes/acknowledge',
    description: 'CommandCenterController: PATCH /command-center/shift-notes/acknowledge',
    domain: 'operations',
    featureGate: 'command_center',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/driver-unavailability',
    description: 'DriverUnavailabilityController: POST /driver-unavailability',
    domain: 'operations',
    featureGate: 'horizon',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/ifta/fuel',
    description: 'IftaController: POST /ifta/fuel',
    domain: 'operations',
    featureGate: 'ifta',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: null, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/ifta/mileage',
    description: 'IftaController: POST /ifta/mileage',
    domain: 'operations',
    featureGate: 'ifta',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/notifications/dismiss-all-read',
    description: 'NotificationsController: POST /notifications/dismiss-all-read',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: null, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/notifications/mark-all-read',
    description: 'NotificationsController: POST /notifications/mark-all-read',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: null, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/routes/geocode-stops',
    description: 'RoutePlanningController: POST /routes/geocode-stops',
    domain: 'operations',
    featureGate: 'route_planning',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/routes/plan',
    description: 'RoutePlanningController: POST /routes/plan',
    domain: 'operations',
    featureGate: 'route_planning',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/shield/audit',
    description: 'ShieldController: POST /shield/audit',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PATCH', path: '/shield/findings/bulk-resolve',
    description: 'ShieldController: PATCH /shield/findings/bulk-resolve',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/shield/rules',
    description: 'ShieldController: POST /shield/rules',
    domain: 'operations',
    featureGate: 'shield',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/support/tickets',
    description: 'SupportController: POST /support/tickets',
    domain: 'operations',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: null, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/vehicle-unavailability',
    description: 'VehicleUnavailabilityController: POST /vehicle-unavailability',
    domain: 'operations',
    featureGate: 'horizon',
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },

  // ═══════════════════════════════════════════════════════
  // PLATFORM
  // ═══════════════════════════════════════════════════════
  {
    method: 'GET', path: '/add-ons',
    description: 'AddOnsController: GET /add-ons',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/add-ons/my-add-ons',
    description: 'AddOnsController: GET /add-ons/my-add-ons',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/add-ons/my-requests',
    description: 'AddOnsController: GET /add-ons/my-requests',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/admin/add-on-requests',
    description: 'AddOnsRequestAdminController: GET /admin/add-on-requests',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/broadcasts',
    description: 'AnnouncementsController: GET /admin/broadcasts',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/feedback',
    description: 'FeedbackAdminController: GET /admin/feedback',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/feedback/stats',
    description: 'FeedbackAdminController: GET /admin/feedback/stats',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/admin/feedback/tenants',
    description: 'FeedbackAdminController: GET /admin/feedback/tenants',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/api-keys',
    description: 'ApiKeysController: GET /api-keys',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/broadcasts/active',
    description: 'BroadcastsPublicController: GET /broadcasts/active',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/feature-flags',
    description: 'FeatureFlagsController: GET /feature-flags',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/feedback',
    description: 'FeedbackController: GET /feedback',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/invitations',
    description: 'UserInvitationsController: GET /invitations',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/oauth/clients',
    description: 'OAuthClientsController: GET /oauth/clients',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/onboarding/status',
    description: 'OnboardingController: GET /onboarding/status',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/plans',
    description: 'PlansController: GET /plans',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/plans/my-plan',
    description: 'PlansController: GET /plans/my-plan',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/reference-data',
    description: 'ReferenceDataController: GET /reference-data',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 200, CUSTOMER: 200, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/settings/admin',
    description: 'SuperAdminPreferencesController: GET /settings/admin',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/settings/alerts',
    description: 'AlertConfigController: GET /settings/alerts',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/settings/operations',
    description: 'OperationsSettingsController: GET /settings/operations',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/settings/operations/defaults',
    description: 'OperationsSettingsController: GET /settings/operations/defaults',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 200, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'GET', path: '/tenants',
    description: 'TenantsController: GET /tenants',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 200 },
  },
  {
    method: 'GET', path: '/users',
    description: 'UsersController: GET /users',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 200, OWNER: 200, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/admin/broadcasts',
    description: 'AnnouncementsController: POST /admin/broadcasts',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: null },
  },
  {
    method: 'POST', path: '/admin/feedback/bulk-categorize',
    description: 'FeedbackAdminController: POST /admin/feedback/bulk-categorize',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: null },
  },
  {
    method: 'POST', path: '/feedback',
    description: 'FeedbackController: POST /feedback',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: null, ADMIN: null, OWNER: null, DRIVER: null, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/invitations',
    description: 'UserInvitationsController: POST /invitations',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/oauth/clients',
    description: 'OAuthClientsController: POST /oauth/clients',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: null },
  },
  {
    method: 'PUT', path: '/settings/admin',
    description: 'SuperAdminPreferencesController: PUT /settings/admin',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: 403, OWNER: 403, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: null },
  },
  {
    method: 'PUT', path: '/settings/alerts',
    description: 'AlertConfigController: PUT /settings/alerts',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'PUT', path: '/settings/operations',
    description: 'OperationsSettingsController: PUT /settings/operations',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/settings/operations/reset',
    description: 'OperationsSettingsController: POST /settings/operations/reset',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
  {
    method: 'POST', path: '/users',
    description: 'UsersController: POST /users',
    domain: 'platform',
    featureGate: null,
    expectations: { DISPATCHER: 403, ADMIN: null, OWNER: null, DRIVER: 403, CUSTOMER: 403, SUPER_ADMIN: 403 },
  },
];
